package cook.entities;

public class RestockRequest {
    private final String ingredientName;
    private final int quantity;
    private boolean isDelivered;
    public boolean isAutoGenerated;

    public RestockRequest(String ingredientName, int quantity, boolean isAutoGenerated) {
        this.ingredientName = ingredientName;
        this.quantity = quantity;
        this.isDelivered = false;
        this.isAutoGenerated = isAutoGenerated;
    }

    public String getIngredientName() {
        return ingredientName;
    }

    public int getQuantity() {
        return quantity;
    }

    public boolean isDelivered() {
        return isDelivered;
    }


    public void markAsDelivered() {
        this.isDelivered = true;
    }
}
